### ISSUE TITLE
Allow custom PPK_ASSERT_DEBUG_BREAK

### ISSUE THREAD

**Issue by jwdevel** [gpakosz/PPK_ASSERT#10]
In the situation where the assert wants to break into the debugger, there is currently some hardcoded choice of using `__debugbreak`, `raise(SIGTRAP)`, etc. depending on platform.

This is not bad, but it would be nice to let the user `#define` their own handling for that situation.

For instance, one could use the [debugbreak](https://github.com/scottt/debugbreak) code, which has some more nuanced platform checks, and can use `int3` and other methods.

**Comment by gpakosz** [comment]
Hello @jwdevel 👋

Would the `gh-10` branch work for you?

**Comment by jwdevel** [comment]
Yes, that works for me (:

You might want to add a description in the README for newcomers, but OK either way for me.
